import Link from "next/link";

export const metadata = {
  title: "Terms of Service — Grantaria",
  description:
    "The short, honest terms for using Grantaria. Free to use, verify deadlines yourself, no warranties.",
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-[820px] px-6 sm:px-10 py-12 lg:py-20">
      <Link
        href="/"
        className="inline-flex items-center gap-2 text-sm text-fg-muted hover:text-cyan transition-colors"
      >
        <span aria-hidden>←</span> Home
      </Link>

      <header className="mt-8">
        <span className="badge-pill">
          <span className="w-2 h-2 rounded-full bg-cyan" />
          Terms of Service
        </span>
        <h1 className="mt-5 font-extrabold text-4xl sm:text-5xl lg:text-6xl tracking-[-0.02em] leading-[1.05]">
          The <span className="gradient-text">house rules.</span>
        </h1>
        <p className="mt-5 text-fg-muted text-sm font-mono uppercase tracking-[0.18em]">
          Last updated: May 16, 2026
        </p>
      </header>

      <div className="mt-10 prose-content text-lg text-fg-soft leading-relaxed space-y-6">
        <p>
          The short version: Grantaria is a free scholarship-matching tool built by one
          person. We do our best to keep the data accurate, but you have to verify deadlines
          on the official source before you apply. Use it as a starting point, not a finish
          line.
        </p>

        <h2 className="text-2xl font-bold text-fg pt-4">By using the site, you agree to these terms</h2>
        <p>
          Visiting <strong className="text-fg">grantaria.com</strong>{" "}
          means you&apos;ve read and accepted what&apos;s on this page. If you don&apos;t agree, don&apos;t use
          the site.
        </p>

        <h2 className="text-2xl font-bold text-fg pt-4">What you can use it for</h2>
        <p>
          Personal scholarship research. Browse colleges, build a profile, view AI matches,
          click through to apply on the official scholarship site. That&apos;s the whole
          intended use.
        </p>

        <h2 className="text-2xl font-bold text-fg pt-4">What you can&apos;t do</h2>
        <ul className="space-y-2 ml-6 list-disc marker:text-fg-muted">
          <li>Scrape, copy, or republish the scholarship database</li>
          <li>Use automated tools to hammer the AI matching endpoint</li>
          <li>Resell or relabel the service as your own</li>
          <li>Try to break, attack, or reverse-engineer the site</li>
          <li>Impersonate someone else when emailing us</li>
        </ul>

        <h2 className="text-2xl font-bold text-fg pt-4">No guarantees on accuracy</h2>
        <p>
          Every scholarship in our database is hand-verified against its official source on
          the date shown as <em>&ldquo;Last verified&rdquo;</em>. But:
        </p>
        <ul className="space-y-2 ml-6 list-disc marker:text-fg-muted">
          <li>Deadlines change. Annual scholarships sometimes shift dates year-over-year.</li>
          <li>Eligibility rules update without notice.</li>
          <li>Some scholarships pause or end without us catching it immediately.</li>
        </ul>
        <p>
          <strong className="text-fg">
            Always confirm the deadline, eligibility, and application URL on the official
            source before you apply.
          </strong>{" "}
          Treat what you see here as a curated starting list, not a guaranteed list of awards
          you&apos;ll receive.
        </p>

        <h2 className="text-2xl font-bold text-fg pt-4">No guarantees on AI matches</h2>
        <p>
          The AI scoring (the &ldquo;why you fit&rdquo; explanations) is generated by
          Anthropic&apos;s Claude API based on your profile and the scholarship&apos;s
          eligibility text. It&apos;s a smart helper, not an oracle. A 95% match doesn&apos;t
          guarantee you&apos;ll win, and a 60% match doesn&apos;t mean don&apos;t apply.
        </p>

        <h2 className="text-2xl font-bold text-fg pt-4">No warranties</h2>
        <p>
          The service is provided <strong className="text-fg">&ldquo;as is&rdquo;</strong>,
          without warranties of any kind — no guarantees of accuracy, uptime, fitness for a
          particular purpose, or non-infringement. We make a good-faith effort to keep the
          site online and the data fresh, but software breaks and life happens.
        </p>

        <h2 className="text-2xl font-bold text-fg pt-4">Limitation of liability</h2>
        <p>
          To the maximum extent allowed by law, Grantaria and its operator are not
          liable for any indirect, incidental, or consequential damages — including missed
          scholarship deadlines, denied applications, or lost opportunities — arising out of
          your use of the site. Because the service is free, the maximum aggregate liability
          is capped at <strong className="text-fg">$0</strong>.
        </p>

        <h2 className="text-2xl font-bold text-fg pt-4">Changes</h2>
        <p>
          We can change, pause, or shut down the service at any time. If we make material
          changes to these terms, we&apos;ll update the &ldquo;Last updated&rdquo; date and
          post a note on the site.
        </p>

        <h2 className="text-2xl font-bold text-fg pt-4">Governing law</h2>
        <p>
          These terms are governed by the laws of the State of Florida. Any disputes will be
          handled in the appropriate courts of Alachua County, Florida.
        </p>

        <h2 className="text-2xl font-bold text-fg pt-4">Operator</h2>
        <p>
          Grantaria is operated by <strong className="text-fg">Zac Martus</strong>, a
          Florida-based individual. Contact:{" "}
          <a className="text-cyan hover:underline" href="mailto:hi@grantaria.com">
            hi@grantaria.com
          </a>
          .
        </p>
      </div>

      <div className="mt-16 pt-10 border-t border-border flex flex-wrap items-center justify-between gap-4 text-sm text-fg-muted">
        <Link href="/privacy" className="hover:text-cyan transition-colors">
          ← Read the Privacy Policy
        </Link>
        <Link href="/" className="hover:text-cyan transition-colors">
          Back to homepage
        </Link>
      </div>
    </div>
  );
}
